name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO111MODULE: "on"
  CGO_ENABLED: "0"
  GOPRIVATE: "github.com/winchci"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - uses: actions/checkout@v2

    - uses: actions/cache@v2.1.6
      with:
        path: /home/runner/go/pkg/mod
        key: v2-go-mod-${{ hashFiles('go.sum') }}
        restore-keys: v2-go-mod-

    - name: Build winch
      run: |
        go mod download
        go test ./...
        go build -o ./winch ./cmd/winch/main.go

    - run: ./winch ci
