name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          goos: linux
        - os: macos-latest
          goos: darwin
    env:
      GO111MODULE: "on"
      CGO_ENABLED: "0"
      GOOS: ${{ matrix.goos }}
      GOPRIVATE: "github.com/winchci"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: /home/runner/go/pkg/mod
        key: v1-go-mod-${{ matrix.goos }}-${{ hashFiles('go.sum') }}
        restore-keys: v1-go-mod-${{ matrix.goos }}
    - name: Build winch
      run: |
        mkdir -p bin/${{matrix.goos}}
        go mod download
        go test ./...
        go get -u \
            github.com/kisielk/errcheck \
            golang.org/x/tools/cmd/goimports \
            golang.org/x/lint/golint \
            github.com/securego/gosec/cmd/gosec \
            golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow \
            honnef.co/go/tools/cmd/staticcheck
        go build -o bin/${{matrix.goos}}/winch ./cmd/winch/main.go
        go build -o bin/${{matrix.goos}}/winch-go-errcheck github.com/kisielk/errcheck
        go build -o bin/${{matrix.goos}}/winch-go-imports golang.org/x/tools/cmd/goimports
        go build -o bin/${{matrix.goos}}/winch-go-lint golang.org/x/lint/golint
        go build -o bin/${{matrix.goos}}/winch-go-sec github.com/securego/gosec/cmd/gosec
        go build -o bin/${{matrix.goos}}/winch-go-shadow golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
        go build -o bin/${{matrix.goos}}/winch-go-staticcheck honnef.co/go/tools/cmd/staticcheck
    - uses: actions/upload-artifact@v1
      with:
        name: winch-${{matrix.goos}}
        path: bin/${{matrix.goos}}/

  release:
    name: Release
    if: ${{ github.ref }} == "master"
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: winch-linux
        path: bin
    - run: ./bin/linux/winch ci
