name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO111MODULE: "on"
  CGO_ENABLED: "0"
  GOPRIVATE: "github.com/winchci"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  SNYK_AUTH_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - uses: actions/checkout@v3.0.2

    - uses: actions/cache@v3.0.10
      with:
        path: /home/runner/go/pkg/mod
        key: v3-go-mod-${{ hashFiles('go.sum') }}
        restore-keys: v3-go-mod-

    - name: Build winch
      run: |
        go mod download
        go test ./...
        go build -o ./winch ./cmd/winch/main.go
        mkdir -p ~/.docker/cli-plugins
        curl https://github.com/docker/scan-cli-plugin/releases/latest/download/docker-scan_linux_amd64 -L -s -S -o ~/.docker/cli-plugins/docker-scan
        chmod +x ~/.docker/cli-plugins/docker-scan

    - run: ./winch ci
